#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - git
  - unzip
  - nginx
  - nginx-full
  - nodejs

# create the ghost group
groups:
  - ghost

# Install Ghost, for production, consider pinning to stable versions
runcmd:
  - apt-get update -y
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - chown -R ubuntu:ubuntu /home/ubuntu
  - bash /home/ubuntu/ghost.sh
  
# Add default auto created user to docker group
system_info:
  default_user:
    name: ubuntu
    groups: [ghost]

# Enable ipv4 forwarding, required on CIS hardened machines
# Install Ghost
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /home/ubuntu/ghost.sh
    permissions: '0755'
    owner: ubuntu:ubuntu
    content: |
      #!/bin/bash

      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      echo \"deb https://dl.yarnpkg.com/debian/ stable main\" | sudo tee /etc/apt/sources.list.d/yarn.list
      sudo apt-get update && sudo apt-get install yarn
      wget https://github.com/TryGhost/Ghost/releases/download/3.41.8/Ghost-3.41.8.zip
      sudo unzip -d /var/www/ghost Ghost-3.41.8.zip
      cd /var/www/ghost/
      sudo yarn install --production
      sleep 1
      sudo chown -R ubuntu:ubuntu /var/www/ghost/
      cat <<FILEXXX > /var/www/ghost/core/server/config/env/config.production.json
      ${data.template_file.ghost-config.rendered}
      FILEXXX
      cd /var/www/ghost/
      yarn global add knex-migrator
      NODE_ENV=production yarn run knex-migrator init
      sleep 1
      adduser --disabled-password --shell /bin/bash --gecos 'Ghost application' ghost
      chown -R ghost:ghost /var/www/ghost/
      touch /etc/nginx/sites-available/ghost && sudo chown ubuntu:ubuntu /etc/nginx/sites-available/ghost
      touch /etc/systemd/system/ghost.service && sudo chown ubuntu:ubuntu /etc/systemd/system/ghost.service
      cat <<FILEXXX > /etc/nginx/sites-available/ghost
      ${data.template_file.nginx-site-config.rendered}
      FILEXXX
      sudo cat <<FILEXXX > /etc/systemd/system/ghost.service
      FILEXXX
      ${data.template_file.service-config.rendered}
      ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost
      rm /etc/nginx/sites-enabled/default
      systemctl enable ghost.service
      systemctl start ghost.service
      service nginx restart
      sleep 1